/*

 SKELLY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char skelly[] =
{
  0x7C,0x7C,0x82,0x82,0x82,0x82,0x82,0xEE,
  0x82,0xAA,0x44,0x54,0x44,0x54,0x38,0x38,
  0x7C,0x7C,0x82,0x82,0x82,0xEE,0x82,0xAA,
  0x82,0x82,0x44,0x54,0x44,0x54,0x38,0x38
};

/* End of SKELLY.C */
